### ISSUE TITLE
OpenCV Position tracking

### ISSUE THREAD

**Issue by RyanSchw** [RyanSchw/UncommonHacks#1]
- [x] View camera feed
- [x] Visualize XY cords
- [x] Visualize Relative speed/acceleration
